name: manage-azure-policy-e11ab2fe
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/diag-settings/initiatives/Apply_Diagnoistic_settings_To_all_Applicable_resources_2edf69e108a541899f509380/**'
#      - .github/workflows/manage-azure-policy-e11ab2fe.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e11ab2fe}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/diag-settings/initiatives/Apply_Diagnoistic_settings_To_all_Applicable_resources_2edf69e108a541899f509380/**
